### PR TITLE
Improve record caller dramatically and fix some warnings and calls to deprecated functions

### PR DESCRIPTION
**Pull request by Tofandel**
I've basically removed the debug backtrace from the call and instead moved the logic to the record_caller function which will do less heavy debug backtrace

TODO maybe add a condition in record_caller to proceed only when on the tools.php page (only place where it's used I think but need confirmation)

I've also added a parameter to 2 functions that is only used internally to make sure the record caller is not called because the caller would then be redux framework and not be recorded

Additionnaly I fixed some typos in comments and changed some calls to deprecated functions to their new non camel case counterpart

### CODE REVIEW

**Comment by Tofandel** [comment]
> wp_get_active_and_valid_plugins()
> 
> This function’s access is marked private. This means it is not intended for use by plugin or theme developers, only in other core functions. It is listed here for completeness.

Sad because it's doing exactly the necessary checks on those options and on the multisite plugins
Seems way cleaner than the get_option('active_plugins')

Reverted this part anyway

**Comment by Tofandel** [comment]
> // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotValidated
> 
> This isn't acceptable. These are correct ways of fixing this without adding this exception. Also, type safe comparisons are a must. WPCS should have caught that too
> 
> See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Fixing-errors-for-input-data

My bad I forgot to check that the get is not empty, didn't get why this warning wouldn't go away

**Comment by Tofandel** [comment]
Okay this is done

My test unit build is passing, no more warnings

Checked the health page and everything is there

**Comment by dovy** [comment]
Please make sure this code work on PHP 5.2+

**Comment by Tofandel** [comment]
The only thing that has a difference between php 5.2 and php 5.4 here is debug_backtrace, the 2 parameters provided were added, but except taking more memory because it will build the entire debug tree with the parameters passed to the functions as well, this is not gonna change anything

**Comment by Tofandel** [comment]
image

I also added the opt name in the about page

**Comment by kprovance** [comment]
I manually patched all this in.  Thank you! 

I spoke to Dovy.  We really do not want any more pull requests during the beta.  It takes me WAY longer to test and vet this stuff, and I would prefer to propose and discuss changes/improvements/fixes on the issue tracker.  it will save me a lot of time.   Plus you don't have to worry about WPCS. 

Thanks again!

**Pull request closed without merging**
