### PR TITLE
Metabox fix and PHP 8 notices

### PR DESCRIPTION
**Pull request by kprovance**

### CODE REVIEW

**Comment by mohammedeisa** [comment]
Thanks, @kprovance for your collaboration. May I ask you what this PR fixes?

**Comment by kprovance** [comment]
Missing entries in Redux_Core::$server that metaboxes requires to work properly.  At some point, that variable was global, now it's a specific array of values, and the ones metaboxes needs were missing.  Everything else was PHP 8.0 barking deprecation notices about default values in functions being out of order or missing.

**Comment by mohammedeisa** [comment]
So, no conflicts with this commit https://github.com/reduxframework/redux-framework-4/pull/195/commits/54d46c82b32fdf1dad4fd11068dfccd14073c0e4 ?

**Comment by kprovance** [comment]
Honestly, I can't tell.  My fork isn't in sync with the master.  I'm not used to syncing forks and pull requests and need to get on the same page with the master.  I'll just close this, sync up and try again.

**Pull request closed without merging**
