### PR TITLE
PHP Composer

### PR DESCRIPTION
**Pull request by Modemod88**

### CODE REVIEW

**Comment by dovy** [comment]
Good call. I'm almost done on a full composer API for the extensions too! 

Just asking your honest thoughts, should we really make a composer specific for version 4, or wait until the official release and put it in the existing repo for Redux? Honest thoughts?

**Comment by dovy** [comment]
@Modemod88 care to hop on slack and chat with me?

**Comment by dovy** [comment]
@Modemod88 Can we chat sometime soon?

**Comment by bosconian-dynamics** [comment]
I've been working with v4 with a GitHub repo with the following configuration:

```json
{
    "extra": {
        "installer-paths": {
            "vendor/{$vendor}/{$name}": ["type:wordpress-plugin"]
        }
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/reduxframework/redux-framework-4"
        }
    ],
    "require": {
        "reduxframework/redux-framework-4": "dev-master"
    }
}
```
I personally think this is more than adequate up until release - if publishing a separate packagist package is what's on the table, I don't really see a particular need for it.

**Comment by dovy** [comment]
Appreciate that @bosconian-dynamics. Did a soft release today. Working through a few more bugs. Hopefully a full release next week or so. ;)

**Pull request closed without merging**
