### PR TITLE
Bug security fixing csrf protection.

### PR DESCRIPTION
**Pull request by lenonleite**
Reverse first condition isset if and change operator AND TO OR.

https://lenonleite.com.br/en/2020/09/19/explorando-vulnerabilidade-em-operadores-logicos-isset-algumacoisa/

### CODE REVIEW

**Comment by dovy** [comment]
Doh, PHPCS says this is bad, ahha. Can you modify it slightly, or do I need to bypass PHPCS?

**Comment by lenonleite** [comment]
hahah, no problem, I can do it. One minute =)

**Comment by lenonleite** [comment]
Hey Dovy,
I was looking but it is scan in all file, many changes to do and I fixed just one line, this is sad =/, break my heart. Because he is using the WordPress code standard not phpcs.

I believe that is more easy ignore phpcs.

**Comment by dovy** [comment]
Thanks for finding that!

**Comment by lenonleite** [comment]
you are welcome. if I can I will help. When you is possible can you update the WordPress Plugin? I don't know if is automatized. @dovy =)

**Comment by dovy** [comment]
In 1 week it will be pushed. Please wait to report on that if you would.  ;). Trying to fix some other pressing issues people just helped me to find.

**Comment by lenonleite** [comment]
Of course I can wait.

**Comment by lenonleite** [comment]
And more, How can I help you with others issues?

**Comment by dovy** [comment]
Please, test away! If you find anything else I'll gladly fix it.  :)

**Pull request merged**
