### PR TITLE
Builder

### PR DESCRIPTION
**Pull request by Tofandel**

### CODE REVIEW

**Comment by kprovance** [comment]
A lot of those I manually patached in weeks ago.  Why are they appearing here again?  I really don;pt want to break code and have to do yet more work.  Is it possible to just pull req the builder stuff and get rid of all that other old stuff?  I already have enough work on my plate...I don;t need this too.  Thanks!

**Comment by Tofandel** [comment]
It's just because the branch was old so I merged with the new code, so the commits still appear yet there is no difference

**Comment by kprovance** [comment]
Well, since we're going to ignore my 'no pull requests' rule, could you at least install PHP CodeSniffer and fix all those errors at one time?  My phone goes off every time it fails and I have to keep the sound on for personal reasons.  Thanks.

**Comment by Tofandel** [comment]
> Tofandel wants to merge 52 commits into reduxframework:redux-builder from Tofandel:builder

Do I have really bad eyes and does it say reduxframework:master?

It's an experiment branch, how else are we supposed to do this? Tired of helping out to be reprimanded.

Dovy will fix phpcs there isn't much but I don't have time

**Comment by dovy** [comment]
Merged with other pull request.  ;)

**Pull request closed without merging**
